/**
 * Author:  Niels.Klazenga <Niels.Klazenga at rbg.vic.gov.au>
 * Created: 18/04/2019
 */

select
  mel_avh_occurrence_core.occurrenceID as "occurrenceID",
  mel_avh_occurrence_core.institutionCode as "institutionCode",
  mel_avh_occurrence_core.collectionCode as "collectionCode",
  mel_avh_occurrence_core.catalogNumber as "catalogNumber",
  'PhysicalObject' as "type",
  'PreservedSpecimen' as "basisOfRecord",
  replace(mel_avh_occurrence_core.recordedBy, ';', ' |') as "recordedBy",
  mel_avh_occurrence_core.recordNumber as "recordNumber",
  'present' as "occurrenceStatus",
  replace(mel_avh_occurrence_core.eventDate, '-00', '') as "eventDate",
  mel_avh_occurrence_core.year as "year",
  mel_avh_occurrence_core.month as "month",
  mel_avh_occurrence_core.day as "day",
  mel_avh_occurrence_core.verbatimEventDate as "verbatimEventDate",
  mel_avh_occurrence_core.habitat as "habitat",
  mel_avh_occurrence_core.country as "country",
  mel_avh_occurrence_core.stateProvince as "stateProvince",
  mel_avh_occurrence_core.waterbody as "waterbody",
  mel_avh_occurrence_core.islandGroup as "islandGroup",
  mel_avh_occurrence_core.island as "island",
  mel_avh_occurrence_core.verbatimLocality as "verbatimLocality",
  mel_avh_occurrence_core.geodeticDatum as "geodeticDatum",
  mel_avh_occurrence_core.decimalLatitude as "decimalLatitude",
  mel_avh_occurrence_core.decimalLongitude as "decimalLongitude",
  mel_avh_occurrence_core.verbatimLatitude as "verbatimLatitude",
  mel_avh_occurrence_core.verbatimLongitude as "verbatimLongitude",
  mel_avh_occurrence_core.georeferenceProtocol as "georeferenceProtocol",
  mel_avh_occurrence_core.coordinateUncertaintyInMeters as "coordinateUncertaintyInMeters",
  mel_avh_occurrence_core.minimumElevationInMeters as "minimumElevationInMeters",
  coalesce(mel_avh_occurrence_core.maximumElevationInMeters, mel_avh_occurrence_core.minimumElevationInMeters) as "maximumElevationInMeters",
  mel_avh_occurrence_core.verbatimElevation as "verbatimElevation",
  mel_avh_occurrence_core.minimumDepthInMeters as "minimumDepthInMeters",
  coalesce(mel_avh_occurrence_core.maximumDepthInMeters, mel_avh_occurrence_core.minimumDepthInMeters) as "maximumDepthInMeters",
  mel_avh_occurrence_core.georeferencedBy as "georeferencedBy",
  mel_avh_occurrence_core.georeferencedDate as "georeferencedDate",
  mel_avh_occurrence_core.georeferenceRemarks as "georeferenceRemarks",
  mel_avh_occurrence_core.scientificName as "scientificName",
  mel_avh_occurrence_core.scientificNameAuthorship as "scientificNameAuthorship",
  'ICBN' as "nomenclaturalCode",
  mel_avh_occurrence_core.taxonRank as "taxonRank",
  mel_avh_occurrence_core.kingdom as "kingdom",
  mel_avh_occurrence_core.phylum as "phylum",
  mel_avh_occurrence_core.class as "class",
  mel_avh_occurrence_core.order as "order",
  mel_avh_occurrence_core.family as "family",
  mel_avh_occurrence_core.genus as "genus",
  mel_avh_occurrence_core.specificEpithet as "specificEpithet",
  mel_avh_occurrence_core.taxonRemarks as "taxonRemarks",
  mel_avh_occurrence_core.identifiedBy as "identifiedBy",
  mel_avh_occurrence_core.identificationQualifier as "identificationQualifier",
  replace(mel_avh_occurrence_core.dateIdentified, '-00', '') as "dateIdentified",
  mel_avh_occurrence_core.identificationRemarks as "identificationRemarks",
  mel_avh_occurrence_core.typeStatus as "typeStatus",
  mel_avh_occurrence_core.associatedSequences as "associatedSequences"
from mel_avh_occurrence_core;

